### ISSUE TITLE
unable to resolve an item in cache

### ISSUE THREAD

**Issue by jeanetteclark** [boettiger-lab/taxadb-cache#1]
Hi @cboettig - after much digging, I think I have found the source of failing  tests on the `EML` package.

I've been  trying to run `  taxon_coverage <- set_taxonomicCoverage(c("Macrocystis pyrifera"),expand = TRUE)`

I'm getting a warning from `contentId` saying 

> No sources found for hash://sha256/ae98e3de1cadd69c064aa7aeb26b89251b49926207d41f8185af28d5f7a8853d

Which corresponds to this entry in [prov.json doc](https://raw.githubusercontent.com/boettiger-lab/taxadb-cache/master/prov.json).

```
"id": "hash://sha256/ae98e3de1cadd69c064aa7aeb26b89251b49926207d41f8185af28d5f7a8853d",
      "type": "Distribution",
      "description": "output data",
      "format": "application/gzip",
      "identifier": "hash://sha256/ae98e3de1cadd69c064aa7aeb26b89251b49926207d41f8185af28d5f7a8853d",
      "title": "dwc_itis.tsv.gz",
      "byteSize": 15347750,
      "compressFormat": "gzip",
      "wasDerivedFrom": "hash://sha256/64355c3cc6d64c7df6dad588678ce8f69e4352d059c182cbdc28621669420ecc",
      "wasGeneratedAtTime": "2021-08-09 16:42:45",
      "wasGeneratedBy": "urn:uuid:16843b1a-7ab7-41b9-a604-78d84e8e854f"
```

Running: 

```
x <- unlist(jsonlite::read_json("https://raw.githubusercontent.com/boettiger-lab/taxadb-cache/master/prov.json"), recursive = TRUE, use.names = FALSE)
ids <- unique(x[grepl("hash://sha256/.*", x)])
lapply(ids, contentid::resolve, store=TRUE)
```

Returns 17 similar warnings.

I think my detective work might end here - any insight on where this  file is supposed to be and why it appears  to be gone would be helpful.

**Comment by cboettig** [comment]
Sorry, can you try either using the (dev) GitHub versions of `contentid` or `taxadb` instead?
(patches for both have been submitted to CRAN but have been stuck in queue for a while...)

**Comment by jeanetteclark** [comment]
Thanks @cboettig - switching to the dev versions has them pass locally. I'm going to close this  issue, and I  made a note in https://github.com/ropensci/EML/pull/333
